#
# This is free software, lisence use MIT.
# 

name: Merge-Upstream
on:
  push:
    paths:
      - '.github/workflows/sync.yml'
      - '.gitignore'
      - '.diy/**'
  schedule:
    - cron: 5 */12 * * *
  workflow_dispatch:
    inputs:
      ssh:
        description: 'ssh'
        required: false
        default: 'false'
  watch:
    types: started
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Syn upstream
      run: |
        shopt -s extglob
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name ".diy"` >/dev/null 2>&1
        function git_clone() (
          git clone --depth 1 $1 $2 || true
        )
        function git_branch_clone() (
          git clone --depth=1 -b $1 $2 || true
        )
        function git_sparse_clone() (
          branch="$1" rurl="$2" localdir="$3" && shift 3
          git clone -b $branch --depth 1 --filter=blob:none --sparse $rurl $localdir
          cd $localdir
          git sparse-checkout init --cone
          git sparse-checkout set $@
          mv -n $@ ../
          cd ..
          rm -rf $localdir
          )
        function mvdir() {
        mv -n `find $1/* -maxdepth 0 -type d` ./
        rm -rf $1
        }
        (
        svn co https://github.com/Twinzo1/AdGuardHome/trunk/luci-app-adguardhome &
        svn co https://github.com/messense/aliyundrive-webdav/trunk/openwrt/luci-app-aliyundrive-webdav
        svn co https://github.com/coolsnowwolf/luci/trunk/applications/luci-app-adbyby-plus
        svn co https://github.com/281677160/openwrt-package/trunk/filebrowser
        svn co https://github.com/281677160/openwrt-package/trunk/luci-app-filebrowser
        svn co https://github.com/281677160/openwrt-package/trunk/luci-app-fileassistant
        svn co https://github.com/coolsnowwolf/luci/trunk/applications/luci-app-filetransfer
        git clone --depth 1 https://github.com/jerrykuku/luci-app-jd-dailybonus
        
        svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash &
        
        git clone --depth 1 https://github.com/zzsj0928/luci-app-pushbot
        svn co https://github.com/coolsnowwolf/luci/trunk/applications/luci-app-ttyd
        
        svn co https://github.com/coolsnowwolf/luci/trunk/applications/luci-app-unblockmusic      
      

        svn co https://github.com/xiaoqingfengATGH/luci-theme-infinityfreedom/trunk/luci-theme-infinityfreedom
        
        git clone --depth 1 https://github.com/iwrt/luci-app-ikoolproxy
  
         git clone --depth 1 https://github.com/kongfl888/luci-app-timedreboot
        ) &
        (
        git_sparse_clone master "https://github.com/coolsnowwolf/packages" "ledepackages" \
        net/iperf3 admin/netdata
        )     
        git clone --depth=1 -b 18.06 https://github.com/jerrykuku/luci-theme-argon
        git clone --depth=1 -b lede https://github.com/pymumu/luci-app-smartdns
        #git_clone https://github.com/281677160/luci-app-autoupdate
        #svn export https://github.com/coolsnowwolf/luci/trunk/applications/luci-app-unblockmusic
        #svn export https://github.com/coolsnowwolf/packages/trunk/multimedia/UnblockNeteaseMusic-Go
        #svn export https://github.com/coolsnowwolf/packages/trunk/multimedia/UnblockNeteaseMusic
        for ipk in $(ls applications); do
        	if [[ $(ls -l applications/$ipk/po | wc -l) -gt 3 ]]; then
        		rm -rf applications/$ipk
        	fi
        done
        
    - name: Delete duplicated packages
      continue-on-error: true
      run: |
        shopt -s extglob
        mv -n openwrt-passwall/* ./ ; rm -Rf openwrt-passwall
        mv -n helloworld/* ./ ; rm -Rf helloworld
        mv -n openwrt-smartdns smartdns
        cp -rf .diy/packages/* ./ || true
        rm -Rf */.git
        
    - name: Apply patches
      continue-on-error: true
      run: |
        find ".diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch"
        
    - name: Modify
      continue-on-error: true
      run: |
        bash .diy/create_acl_for_luci.sh -a >/dev/null 2>&1 || true
        bash .diy/convert_translation.sh -a >/dev/null 2>&1 || true
      
    - name: SSH connection to Actions
      uses: kiddin9/debugger-action@master
      if: github.event.inputs.ssh == 'true'

    - name: Apply
      continue-on-error: true
      run: |
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M)"
        git push -f
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3
        
