#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/kiddin9/openwrt-packages/blob/master/.github/workflows/upstream.yml>
#https://github.com/Twinzo1/openwrt-packages/blob/main/.github/workflows/upstream.yml

name: Merge-upstream
on:
  push:
    paths:
      - '.github/workflows/upstream.yml'
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "51288907+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Syn upstream
      run: |
        rm -rf `find -maxdepth 1 -type d -name "[!.]*"`
        git rm -r --cache *
       
        # 下载diy脚本
    
        
        
       

        git clone --depth 1 https://github.com/garypang13/luci-theme-edge &
      


        
      
      
        
        git clone --depth 1 https://github.com/project-lede/luci-app-godproxy &


  



        git clone --depth 1 -b 18.06 https://github.com/jerrykuku/luci-theme-argon &
        git clone --depth 1 https://github.com/jerrykuku/luci-app-argon-config &
        git clone --depth 1 https://github.com/jerrykuku/luci-app-vssr &
      
        git clone --depth 1 https://github.com/jefferymvp/luci-app-koolproxyR &
  
        git clone --depth 1 https://github.com/vernesong/OpenClash && mv -f OpenClash/luci-app-openclash ./ ; rm -Rf OpenClash &

    
        git clone --depth 1 https://github.com/esirplayground/luci-app-poweroff &
   


        svn co https://github.com/Twinzo1/AdGuardHome/trunk/luci-app-adguardhome &
 
 
        svn co https://github.com/xiaoqingfengATGH/luci-theme-infinityfreedom/trunk/luci-theme-infinityfreedom &

        svn export https://github.com/Lienol/openwrt-package/trunk/luci-app-filebrowser

        

        
      
      
    - name: Apply patches
      run: |
        #sed -i "s/\r//g" open-app-filter/src/appfilter_ubus.c
        #find "diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch"

    - name: Modify
      run: |
        # 清理石像鬼插件
        rm -rf *gargoyle*
        # 清理重复或非必要文件
        rm -Rf */.git */.svn qt5 openwrt-{chinadns*,simple-obfs,v2ray-plugin,fullconenat,dnsforwarder} cups* subweb \
        mt-drivers coremark npc luci-app-{flowoffload,sfe,appfilter,unblockneteasemusic*,adbyby-plus,advancedsetting,softethervpn,chinadns,docker,samba4} fcgiwrap \
        ddns-scripts_{aliyun,dnspod} UnblockNeteaseMusicGo ipv6-helper adbyby ChinaDNS luci-theme-netgear
        
        
        
        rm -f subconverter/patches/010-missing-header.patch
        sed -i 's?../../luci.mk?$(TOPDIR)/feeds/luci/luci.mk?g' */Makefile
        sed -i 's?../../lang?$(TOPDIR)/feeds/packages/lang?g' */Makefile
        bash diy/create_acl_for_luci.sh -a || true
        bash diy/convert_translation.sh -a || true
        sed -i 's/ca-certificates/ca-bundle/g' */Makefile
        sed -i 's/+libcap /+libcap +libcap-bin /' luci-app-openclash/Makefile
        sed -i 's/@GHCODELOAD/https:\/\/codeload.github.com/' */Makefile
        find */luasrc/view/ -maxdepth 2 -name "*.htm" | xargs -i sed -i 's?"http://" + window.location.hostname?window.location.protocol + "//" + window.location.hostname?g' {}
        find ./*/ -maxdepth 1 -name "Makefile" ! -path "*tinyfecvpn*" ! -path "*gowebdav*" | xargs -i sed -i "s/PKG_HASH:=.*/PKG_HASH:=skip/g" {}
        sed -i 's/SUBDIRS=/M=/g' */Makefile
        # sed -i 's/\(add ucitrack \(.*\)\)/\1\n\tservice \2 enable/g' luci-app*/root/etc/uci-defaults/*

    - name: Apply
      run: |
        git add .
        git commit -m "update" || true
        git push
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
